project:
  type: website

website:
  title: "UNSW codeRs"
  navbar:
    logo: images/logo.png       
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People
      - href: mentoring.qmd
        text: Mentoring
      - href: workshops.qmd
        text: Workshops
      - href: resources.qmd
        text: Resources
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



